### PR TITLE
Issue Preventing Checkout with Configurable Products in Low Stock

### LINKED ISSUE #59: Issue Preventing Checkout with Configurable Products in Low Stock
**Describe the bug**
Bug When One Product in Stock. No order can be placed.  After investigating the issue, it's observed that no problems occur with MSI + Adyen or with Hyva theme + MSI. However, the issue arises when the compatibility module is involved. Specifically, when attempting to add a configurable product with limited stock (e.g., 2 items), the shipping methods do not appear on the checkout page. Interestingly, if the pre-selected shipping method is not changed, the issue does not occur.
In the code, two calls are made to CartItemPersister to collect `BuyRequestData` using the line:
`$buyRequestData = $this->cartItemOptionProcessor->getBuyRequest($productType, $item);`
This `BuyRequestData` can either be a float value or an object. In the first request, it's a float, so no exception is thrown. However, in the second request, it becomes an object. When the system proceeds to update the quote item with the following logic:
`if (is_object($buyRequestData)) { /** Update item product options */ if ($quote->getIsActive()) { $item = $quote->updateItem($itemId, $buyRequestData); } }
`
While updating the quote item, the logic in Quote.php tries to add more products to the quote, same amount as already added to the cart. Since there are no additional items available in stock, this triggers an exception.
`$resultItem = $this->addProduct($product, $buyRequest);`
My observation is that since the configuration is only needed to populate data in the payment block, it may be sufficient to fetch only the specific configurations required for those blocks, rather than retrieving all configurations.

**To Reproduce**
1. Make sure MSI is enabled and set up correctly
2. Make sure you have a configurable product with at least one option that has 1 in stock (note: it will also happen with a larger stock, but 1 might be easier to test)
3. Add the configurable option to your cart and make sure you add all items in stock to the cart
4. Go to the checkout
5. Fill in the form and change the country
6. If you keep the country as it is, the same issue will happen when selecting a (different) shipping method

**Expected behavior**
* It's possible to change the country
* It's possible to select a shipping method

**Actual behavior**
* When changing the country or selecting a shipping method, an error is shown that the requested quantity is not available
* No shipping methods are available anymore and it's impossible for customers to place an order

**Magento version**
2.4.7

**Plugin version**
1.1.0

**Additional context**
* This issue doesn't happen for simple products
* This issue doesn't happen if Adyen is removed (disabling through the admin doesn't solve it)
* I've done quite some research and debugging here and noticed that the issue comes from the Adyen module fetching all the configuration for the checkout in the payment block's constructor (\Adyen\Hyva\Block\PaymentMethod). This results in the additional options being loaded in \Magento\Checkout\Model\DefaultConfigProvider::getQuoteItemData(), which on itself results in the buy request being an object in \Magento\Quote\Model\Quote\Item\CartItemPersister::save() on line 75. Because this is an object, it will update the order item and not just set the new quantity. Through some more steps we will get to \Magento\Quote\Model\Quote\Item::addQy() where the current item quantity is increased with the given quantity (which is also the current quantity).
* Since the configuration is only needed for filling the data in the payment block, it might be enough to just fetch the specific configuration that is needed in these blocks and not fetch all the configurations.

### PR DESCRIPTION
**Pull request by pmarjan-onestic**
## Summary

Issue happens when One Product is in Stock. No order can be placed. After investigating the issue, it's observed that no problems occur with MSI + Adyen or with Hyva theme + MSI. However, the issue arises when the compatibility module is involved. Specifically, when attempting to add a configurable product with limited stock (e.g., 2 items), the shipping methods do not appear on the checkout page. Interestingly, if the pre-selected shipping method is not changed, the issue does not occur.
In the compatibility module, there are two calls to `CartItemPersister`, which processes `BuyRequestData` differently each time:

**First Call:** `BuyRequestData` is returned as a float (indicating, possibly, a single unit or specific quantity).
**Second Call:** `BuyRequestData` is returned as an object (indicating a detailed configuration request, such as specific product options or custom data).
When `BuyRequestData` is treated as an object in the second request, Magento’s `Quote.php` interprets this as a full update request for the cart. It tries to add more of the product to the cart, potentially exceeding the available stock, thus triggering an out-of-stock exception.

Since the configuration is only needed to populate information in the payment block, we might avoid the issue by fetching only the specific configuration data required for that payment block, without altering the existing cart item quantities.

With the proposed solution, The `CompositeConfigProvider` consolidates configurations from various ConfigProviderInterface implementations. By including only the necessary configuration providers, we avoid any unnecessary processing that might interfere with cart items or stock levels.

## Tested scenarios

It's possible to change the country
It's possible to select a shipping method
Successful Payment with the limited quantity in stock for configurable object

Fixes #59

### CODE REVIEW

**Comment by candemiralp** [comment]
Hello @pmarjan-onestic,

Thank you for providing the fix. Is this PR ready to be reviewed? If so, could you please add a brief description about the fix and how these changes lead us to the solution?

Best Regards,
Can

**Comment by pmarjan-onestic** [comment]
hi @candemiralp 

'Adyen\Hyva\Model\Configuration` is a configuration reader that previously used to depend on `Magento\Checkout\Model\CompositeConfigProvider`. This composite provider comes with all sorts of config providers, and one of them (sorry, but cannot remember which) would just do extra work that would turn the buyRequest for the update item from an array into some data object....

Marc's suggestion was something like: _"My observation is that since the configuration is only needed to populate data in the payment block, it may be sufficient to fetch only the specific configurations required for those blocks, rather than retrieving all configurations."

And the PR is now following this idea, practically introducing "Adyen\Hyva\Model\CompositeConfigProvider" instead of "Magento\Checkout\Model\CompositeConfigProvider". The former is custom configured in di.xml to include config provider that are relevant to the adyen usage, making it more targeted and probably more preformance oriented at the same time.

Let me know please if any questions.

**Review by khushboo-singhvi — DISMISSED** [review]

**Comment by candemiralp** [comment]
Hello @pmarjan-onestic,

Thank you for providing a fix for this issue. We are still testing it and this PR will be merged after testing. 

Best Regards,
Can

**Review by ArjenMiedema — APPROVED** [review]
I really like the approach of the custom ConfigProvider. I'm having the issue you mentioned as well. Will check if that is solved with this PR. Would be really awesome to get this working properly.

**Review by candemiralp — APPROVED** [review]

**Review by peterojo — APPROVED** [review]

**Pull request merged**
